- hosts: lab1
  gather_facts: false
  connection: local
#  connection: network_cli
  vars:
    instances: 3
    ports: 100

  tasks:
    - name: test loop
      debug:
        msg: "{{ 'testuser%s' | format(item) }} and {{ ' ports :10%x' | format(item)}}"
      loop: "{{ range(1 ,instances + 1 )|list }}"


