---
# tasks file for am_conf
  - name: Create keys directory for AM
    file:
      path: /etc/alertmanager/keys
      owner: "alertmanager"
      group: "alertmanager"
      mode: '0664'
      state: directory
    tags: am_key_dir
  
  - name: copy key and crt - tasks
    tags: copy_keys
    block:
    - name: copy key file 
#      become: true
      copy:
        src: ./keys/key/{{inventory_hostname}}.key
        dest: /etc/alertmanager/keys/
        owner: alertmanager
        group: alertmanager
        mode: '0644'
  
    - name: copy crt file 
#      become: true
      copy:
        src: ./keys/crt/{{inventory_hostname}}.crt
        dest: /etc/alertmanager/keys/
        owner: alertmanager
        group: alertmanager
        mode: '0644'
